lang: ru-RU
encoding: utf-8
timezone: Asia/Yekaterinburg
title: Рузэль Давлетяров
author: Ruzel Davletyarov
email: ovearub@gmail.com
description: >
  Давлетяров Рузэль Камилевич с. Бураево разработчик программного обеспечения
show_excerpts: false
google_analytics: "UA-122243590-1"
sass:
  style: compressed
permalink: pretty
minima:
  date_format: "%dd.%mm.%Y"
  social_links:
    github: "davletyarov"
    telegram: "buraevo"
theme: minima
plugins:
  - jekyll-seo-tag
